Add scalafix configuration
it fails because of a mis-configuration of the ExplicitReturnTypes rewrite
error: Failed to fix /home/gui/scaladex/scaladex/server/src/main/scala/ch.epfl.scala.index.server/routes/api/PublishApi.scala94.4% [######### ] 17 source files fixed
java.lang.IllegalStateException: Object {} has no field 'explicitReturnTypes'. Did you mean '' instead?
        at metaconfig.Configured.get(Configured.scala:11)
        at scalafix.rewrite.ExplicitReturnTypes.scalafix$rewrite$ExplicitReturnTypes$$isRewriteCandidate$1(ExplicitReturnTypes.scala:95)
        at scalafix.rewrite.ExplicitReturnTypes$$anonfun$rewrite$8.isDefinedAt(ExplicitReturnTypes.scala:118)
        at scalafix.rewrite.ExplicitReturnTypes$$anonfun$rewrite$8.isDefinedAt(ExplicitReturnTypes.scala:116)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:30)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)